export default function params(req, res) {
    res.status(200).json({
        params: req.query
    })
}

// 1) QUANDO SE NOMEIA UM ARQUIVO DE ROTA COM SPREAD (...) - ELE PASSA A ACEITAR VÁRIOS PARÂMETROS
// 2) NUMA ROTA, SE NÃO FOR PASSADO NENHUM PARÂMETRO VAI GERAR ERRO 404, 
//    MAS PARA EVITAR ISSO E TORNAR OPCIONAL, BASTA ACRESCENTAR MAIS UM PAR DE COLCHETES NO MOME DO ARQUIVO DA ROTA